#!/bin/bash

LOCAL_REPO=$1

REMOTE_LOCATION=$2

REMOTE_REPO=$3

if [[ ! -e $LOCAL_REPO/.git ]]; then
  echo "Error: you must input a valid git repo to sync..."
  exit 1
fi

IGNORE_FILE=/tmp/$(basename $LOCAL_REPO).ignore

ssh -t $REMOTE_LOCATION "git -C $REMOTE_REPO ls-files --exclude-standard -oi --directory" > $IGNORE_FILE
rsync -av --omit-dir-times --no-p --exclude-from=$IGNORE_FILE --delete $LOCAL_REPO/ $REMOTE_LOCATION:$REMOTE_REPO
